### ISSUE TITLE
Cljs build broken for new project with a dash (-) in its name

### ISSUE THREAD

**Issue by sp3ctum** [plexus/chestnut#125]
How to reproduce:

```shell
lein new chestnut mika-pong -- --cljx
cd mika-pong
lein cljsbuild once
```

Output:
```
Compiling ClojureScript.
Compiling "resources/public/js/app_test.js" from ["src/cljs" "test/cljs"]...
WARNING: No such namespace: mika_pong.core-test at line 1 test/cljs/mika_pong/test-runner.cljs
Compiling "resources/public/js/app_test.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:test/cljs/mika_pong/test-runner.cljs {:file #<File test/cljs/mika_pong/test-runner.cljs>}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at cljs.compiler$compile_file.invoke(compiler.clj:978)
```

**Comment by sp3ctum** [comment]
I can work around this / fix it by renaming all instances of `mika_pong` to `mika-pong` in each file it is referenced. Also I renamed `core-test.cljs` to `core_test.cljs`, as well as `test-runner.cljs` to `test_runner.cljs`.

After that, running `lein cljsbuild auto` works.

**Comment by slester** [comment]
Relevant bits from leiningen:

```clojure
(defn sanitize
  "Replace hyphens with underscores."
  [s]
  (string/replace s "-" "_"))

(defn name-to-path
  "Constructs directory structure from fully qualified artifact name:
  \"foo-bar.baz\" becomes \"foo_bar/baz\"
  and so on. Uses platform-specific file separators."
  [s]
  (-> s sanitize (string/replace "." java.io.File/separator)))

(defn sanitize-ns
  "Returns project namespace name from (possibly group-qualified) project name:
  mygroup/myproj  => mygroup.myproj
  myproj          => myproj
  mygroup/my_proj => mygroup.my-proj"
  [s]
  (-> s
      (string/replace "/" ".")
      (string/replace "_" "-")))
```

It looks like the relevant bit is around line 87 in src/leiningen/new/chestnut.clj - name-to-path sanitizes but the project namespace is uses sanitize-ns.
