### ISSUE TITLE
New Chestnut project: No client connected to Websocket

### ISSUE THREAD

**Issue by KurtRMueller** [plexus/chestnut#129]
```
╰─➤  lein version
Leiningen 2.5.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM
```

I'm on OS/X Yosemite.

After running `lein chestnut new ifcalc`, I followed along with the included `readme.md`. I've ran `lein repl` and then in the ensuing prompt ran

```clojure
ifcalc.server=> (run)
(browser-repl)
ifcalc.core=> (ns ifcalc.core)
java.io.IOException: No client connected to Websocket
        at weasel.repl.server$send_BANG_.invoke(server.clj:25)
        at weasel.repl.websocket$send_for_eval_BANG_.invoke(websocket.clj:143)
        at weasel.repl.websocket$websocket_eval.invoke(websocket.clj:122)
        at weasel.repl.websocket.WebsocketEnv._evaluate(websocket.clj:35)
        at cljs.repl$evaluate_form.invoke(repl.clj:113)
        at cemerick.piggieback$cljs_eval$fn__5158.invoke(piggieback.clj:115)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at cemerick.piggieback$cljs_eval.invoke(piggieback.clj:97)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at cemerick.piggieback$cljs_repl$fn__5202.doInvoke(piggieback.clj:173)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:388)
        at ifcalc.core$eval31493.invoke(form-init6999026418529545024.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6666)
        at clojure.core$eval.invoke(core.clj:2927)
        at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
        at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
        at clojure.main$repl$fn__6634.invoke(main.clj:257)
        at clojure.main$repl.doInvoke(main.clj:257)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1455.invoke(interruptible_eval.clj:67)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:51)
        at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1497$fn__1500.invoke(interruptible_eval.clj:183)
        at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1490.invoke(interruptible_eval.clj:152)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.io.IOException: No client connected to Websocket
nil
ifcalc.core=> (swap! app-state assoc :text "Interactivity FTW")
java.io.IOException: No client connected to Websocket
        at weasel.repl.server$send_BANG_.invoke(server.clj:25)
        at weasel.repl.websocket$send_for_eval_BANG_.invoke(websocket.clj:143)
        at weasel.repl.websocket$websocket_eval.invoke(websocket.clj:122)
        at weasel.repl.websocket.WebsocketEnv._evaluate(websocket.clj:35)
        at cljs.repl$evaluate_form.invoke(repl.clj:113)
        at cemerick.piggieback$cljs_eval$fn__5158.invoke(piggieback.clj:115)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at cemerick.piggieback$cljs_eval.invoke(piggieback.clj:97)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at cemerick.piggieback$cljs_repl$fn__5202.doInvoke(piggieback.clj:173)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:388)
        at ifcalc.core$eval31495.invoke(form-init6999026418529545024.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6666)
        at clojure.core$eval.invoke(core.clj:2927)
        at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
        at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
        at clojure.main$repl$fn__6634.invoke(main.clj:257)
        at clojure.main$repl.doInvoke(main.clj:257)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1455.invoke(interruptible_eval.clj:67)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:51)
        at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1497$fn__1500.invoke(interruptible_eval.clj:183)
        at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1490.invoke(interruptible_eval.clj:152)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.io.IOException: No client connected to Websocket
nil
```

I hesitated creating an issue for this. However, since it's a brand new Chestnut app, I feel like this could be a bug. I can provide any additional information upon request. Thanks everybody.

**Comment by acron0** [comment]
Yeah, I noticed this too. It's fixed by just refreshing your browser, after running `(browser-repl)`, before entering anything else on the REPL. My guess, from looking at Dev Tools, is that unlike Figwheel, Weasel doesn't retry -- it logs a nasty error and then gives up. I have no idea if it's *meant* to retry, or whether the solution is to amend the README or print something after running `(browser-repl)` which encourages people to refresh their browser at that point.

**Comment by plexus** [comment]
Yeah you should only load the page after `(browser-repl)` has loaded and before doing anything else. At least that's how I've always done it and it seems to work. That's also how it's explained [in the documentation](http://plexus.github.io/chestnut/01_00_getting_started.html)

**Comment by acron0** [comment]
Actually, yes, @plexus is correct. The documentation does state both steps before loading the browser.

**Comment by KurtRMueller** [comment]
Fair enough. I was reading the readme.md that came with the project that isn't as fleshed out or explicit as the documentation @plexus linked.

Before this issue is closed, would any of you two mind explaining why running `(browser-repl)` after you've visited `localhost` will cause the above error? Thanks guys -- and thanks for `chestnut`. It really is a great project for people just getting started with clojurescript.

**Comment by acron0** [comment]
Like I said, as soon as you visit `localhost` weasel attempts a websocket connection. It fails immediately , as the port is not yet open, and does not retry. Post-`(browser-repl)` it can connect fine.

**Comment by plexus** [comment]
Yup, you can think of `(browser-repl)` as starting an extra "server", on a separate port, that's waiting for the browser to connect to it, so that then your repl can send commands to the browser.

**Comment by KurtRMueller** [comment]
Cool, thanks guys.
