### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by geometerJones** [plexus/chestnut#231]
- [x ] I am reporting a bug or problem in Chestnut

Hi, I've created a new Chestnut project.

I've been following the README, running (go) and (cljs-repl), but I've started to run into issues.

When I run (go), I get an error about the address already being used. I ran another instance, but I used (stop) so I'm not sure why this is happening.

Here are the logs:

2018-04-01 20:31:22.570:INFO:oejs.Server:nREPL-worker-3: jetty-9.2.21.v20170120
2018-04-01 20:31:22.572:WARN:oejuc.AbstractLifeCycle:nREPL-worker-3: FAILED ServerConnector@7deeff82{HTTP/1.1}{0.0.0.0:10555}: java.net.BindException: Address already in use

Thanks for your help!

Peter

**Comment by featheredtoast** [comment]
Hi Peter,

That's interesting - The stopped instance sounds like it's still listening on that port. Would it be possible to kill the other instance's repl before creating a second project? That *should* free up that port.

**Comment by geometerJones** [comment]
Thanks Jeff,

After restarting my computer, this error seems to have resolved itself.

I have the cljs-repl running. 

However, when I use the (swap! app-state assoc :text "Hello World!") command, the content in my browser doesn't change.

When I refresh the page, my cljs-repl gets stuck, returning error message

2018-04-03 00:01:15.652:WARN:oejs.HttpChannel:qtp398703912-23: /favicon.ico
java.lang.NullPointerException: Response map is nil
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__4449.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

Will continue debugging, just wondering if this is a familiar occurrence!

Thanks again,
Peter
