### ISSUE TITLE
Less is broken on heroku with chestnut master

### ISSUE THREAD

**Issue by SohumB** [plexus/chestnut#72]
```
       Retrieving compojure/compojure/1.3.1/compojure-1.3.1.jar from clojars
       Retrieving ring/ring-anti-forgery/1.0.0/ring-anti-forgery-1.0.0.jar from clojars
       Retrieving clout/clout/2.1.0/clout-2.1.0.jar from clojars
       Retrieving medley/medley/0.5.3/medley-0.5.3.jar from clojars
       Retrieving com/facebook/react/0.12.2.1/react-0.12.2.1.jar from clojars
       Retrieving om/om/0.8.0-beta5/om-0.8.0-beta5.jar from clojars
       Retrieving sablono/sablono/0.2.22/sablono-0.2.22.jar from clojars
       Retrieving prismatic/om-tools/0.3.9/om-tools-0.3.9.jar from clojars
       Retrieving prismatic/plumbing/0.3.5/plumbing-0.3.5.jar from clojars
       Retrieving prismatic/schema/0.3.1/schema-0.3.1.jar from clojars
       Retrieving weasel/weasel/0.4.2/weasel-0.4.2.jar from clojars
       Compiling project.dev
       Compiling project.server
       java.lang.IllegalAccessError: start-less does not exist, compiling:(server.clj:1:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile1(Compiler.java:7216)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)   
        at clojure.core$load_one.invoke(core.clj:5446)   
        at clojure.core$compile$fn__5071.invoke(core.clj:5652)
        at clojure.core$compile.invoke(core.clj:5651)
        at user$eval9$fn__16.invoke(form-init8647967921244594969.clj:1)
        at user$eval9.invoke(form-init8647967921244594969.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274) 
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)  
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)   
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)  
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
       Caused by: java.lang.IllegalAccessError: start-less does not exist
        at clojure.core$refer.doInvoke(core.clj:3919)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_lib.doInvoke(core.clj:5505) 
        at clojure.lang.RestFn.applyTo(RestFn.java:142)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:805)
        at otherworldimports.server$loading__4958__auto__.invoke(server.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
        ... 28 more
       Exception in thread "main" java.lang.IllegalAccessError: start-less does not exist, compiling:(server.clj:1:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile1(Compiler.java:7216)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$compile$fn__5071.invoke(core.clj:5652)
        at clojure.core$compile.invoke(core.clj:5651)
        at user$eval9$fn__16.invoke(form-init8647967921244594969.clj:1)
        at user$eval9.invoke(form-init8647967921244594969.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274) 
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)  
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)   
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)  
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
       Caused by: java.lang.IllegalAccessError: start-less does not exist
        at clojure.core$refer.doInvoke(core.clj:3919)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_lib.doInvoke(core.clj:5505) 
        at clojure.lang.RestFn.applyTo(RestFn.java:142)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)  
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)  
        at clojure.lang.RestFn.invoke(RestFn.java:805)   
        at otherworldimports.server$loading__4958__auto__.invoke(server.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)  
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
        ... 28 more
       Compilation failed: Subprocess failed
 !     Failed to build.

 !     Push rejected, failed to compile Clojure (Leiningen 2) app

```

**Comment by plexus** [comment]
This needs to be handled the same way as `start-figwheel`, with an empty `start-less` defninition in `env/prod/clj/chestnut/dev.clj`.

**Comment by plexus** [comment]
`start-sass` will have the same issue. Although sass doesn't work on Heroku out of the box anyway.
